apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: icteam.azurecr.io/helloworld:latest
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld
  labels:
    app: helloworld
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"    
spec:
  tls:
  - hosts:
    - helloworld.apps.icteam.be
    secretName: helloworld-tls
  rules:
  - host: helloworld.apps.icteam.be
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld
          servicePort: 8080
